[package]
name = "siena"
description = "A flat-file database and ORM."
repository = "https://git.sr.ht/~asko/siena"
version = "1.1.4"
edition = "2021"
authors = ["Asko Nõmm <ano@ano.ee>"]
license = "MIT"
keywords = ["frontmatter", "yaml", "orm", "database"]
categories = ["database", "filesystem"]

[dependencies]
regex = "1"
comrak = "0.14"
serde = "1.0"
serde_yaml = "0.9"